### ISSUE TITLE
Patch 13.11

### ISSUE THREAD

**Issue by okokingxxx** [shv187/league-zoom-manager#3]
For some reason it doesnt seem to work since the start of this patch, usually pattern scanning is succesful and it sees the league process however whenever I try to use arrows to zoom in or out it just doesn't respond :(

**Comment by shv187** [comment]
Works fine for me :--/
You built the latest version yourself, right?

**Comment by okokingxxx** [comment]
Yeah, but I didn't do anything different to previous times when I built it

**Comment by okokingxxx** [comment]
I am not sure why but it seems to only work if I build the console file but it was definitely a mistake on my end, sorry for bothering you and thank you for this once again :)
