### ISSUE TITLE
New patch scanning issue

### ISSUE THREAD

**Issue by okokingxxx** [shv187/league-zoom-manager#5]
Seems not to work as of the new update. It just scans for the whole game without actually finishing and I wonder what might be the cause of this. Hopefully you can update it if its possible :)

**Comment by shv187** [comment]
Thanks for feedback, fixed in 7df216687bdd89fecac3726c91cb59186c96cfdf :)

**Comment by okokingxxx** [comment]
works perfectly now, thank you!
